---
apiVersion: v1
kind: Service
metadata:
  name: accountstoelastic-svc
  namespace: ecollect
  label:
    app: accountstoelastic
spec:
  selector:
    app: accountstoelastic
  ports:
    - protocol: TCP
      port: 5401
      name: 5401-tcp
      targetPort: 5401
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountstoelastic
  namespace: ecollect
  labels:
    app: accountstoelastic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accountstoelastic
  template:
    metadata:
      labels:
        app: accountstoelastic
    spec:
      containers:
      - name: accountstoelastic
        image: docker.io/migutak/accounts_to_elastic:5.2
        envFrom:
          - configMapRef:
              name: ecol-config
          - secretRef:
                name: ecol-secrets
        ports:
        - containerPort: 5401
        resources:
          requests:
            memory: "1Gi"
            cpu: '500m'
          limits:
            memory: "4Gi"
            cpu: 1