---
apiVersion: v1
kind: Service
metadata:
  name: cacheapi-svc
  namespace: ecollect
spec:
  selector:
    app: cacheapi
  ports:
    - protocol: TCP
      port: 5600
      name: 5600-tcp
      targetPort: 5600

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cacheapi
  namespace: ecollect
  labels:
    app: cacheapi
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cacheapi
  template:
    metadata:
      labels:
        app: cacheapi
    spec:
      containers:
      - name: cacheapi
        image: docker.io/migutak/cache:5.7
        envFrom:
          - configMapRef:
              name: ecol-config
          - secretRef:
                name: ecol-secrets
        ports:
        - containerPort: 5600
        resources:
          requests:
            memory: "2Gi"
            cpu: 1
          limits:
            memory: "4Gi"
            cpu: 2