---
apiVersion: v1
kind: Service
metadata:
  name: docx-svc
  namespace: ecol
  label:
    app: docx
spec:
  selector:
    app: docx
  ports:
    - protocol: TCP
      port: 8004
      name: 8004-tcp
      targetPort: 8004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docx
  namespace: ecol
  labels:
    app: docx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docx
  template:
    metadata:
      labels:
        app: docx
    spec:
      containers:
      - name: docx
        image: docker.io/migutak/docxletters:5.6.1
        envFrom:
          - configMapRef:
              name: ecol-config
          - secretRef:
                name: ecol-secrets
        ports:
        - containerPort: 8004
        resources:
          requests:
            memory: "2Gi"
            cpu: 1
          limits:
            memory: "4Gi"
            cpu: 2