---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ecollectapis-route
  namespace: ecol
  labels:
    app: ecollectapis
spec:
  host: apis-ecol.apps.ocpdev.co-opbank.co.ke
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: ecollectapis-svc
  port:
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ecollectapis-svc
  labels:
    app: ecollectapis
spec:
  selector:
    app: ecollectapis
  ports:
    - protocol: TCP
      name: 8000-tcp
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecollectapis
  namespace: ecol
  labels:
    app: ecollectapis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecollectapis
  template:
    metadata:
      labels:
        app: ecollectapis
    spec:
      containers:
      - name: ecollectapis
        image: docker.io/migutak/ecollect_apis:5.9
        envFrom:
          - configMapRef:
              name: ecol-config
          - secretRef:
                name: ecol-secrets
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "500m"