---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ecollect
  namespace: ecol
  labels:
    app: ecollect
spec:
  host: ecollect-ecol.apps.ocpdev.co-opbank.co.ke
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: ecollect-svc
  port:
    targetPort: 4430
---
apiVersion: v1
kind: Service
metadata:
  name: ecollect-svc
spec:
  selector:
    app: ecollect
  ports:
    - protocol: TCP
      name: 4430-tcp
      port: 4430
      targetPort: 4430

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecollect
  namespace: ecol
  labels:
    app: ecollect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecollect
  template:
    metadata:
      labels:
        app: ecollect
    spec:
      containers:
      - name: ecollect
        image: docker.io/migutak/ecollect:5.2
        ports:
        - containerPort: 4430
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "500m"