---
apiVersion: v1
kind: Service
metadata:
  name: ecollect-svc
  namespace: ecollect
spec:
  selector:
    app: ecollect
  ports:
    - protocol: TCP
      name: 4430-tcp
      port: 4430
      targetPort: 4430
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecollect
  namespace: ecollect
  labels:
    app: ecollect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecollect
  template:
    metadata:
      labels:
        app: ecollect
    spec:
      containers:
      - name: ecollect
        image: docker.io/inteligeninfosys/ecollect-cbi:03062023081555.9
        ports:
        - containerPort: 4430
        resources:
          requests:
            memory: "1Gi"
            cpu: "100m"
          limits:
            memory: "4Gi"
            cpu: "2"