
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/data/minio-o
    server: 172.16.20.139
    #persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: ecol
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: ecol
  labels:
    app: minio
    namespace: ecol
spec:
  ports:
    - port: 9000
      name: 9000-tcp
      targetPort: 9000
  selector:
    app: minio
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: ecol
spec:
  serviceName: "minio"
  selector:
    matchLabels:
      app: minio
  updateStrategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args: ['server','/data']
        env:
        - name: MINIO_ROOT_USER
          value: minio
        - name: MINIO_ROOT_PASSWORD
          value: minio123
        readinessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "200Mi"
            cpu: '100m'
          limits:
            memory: 2Gi
        ports:
          - containerPort: 9005
            hostPort: 9005
          - containerPort: 9000
            hostPort: 9000
        volumeMounts:
          - name: minio-data
            mountPath: /data
  volumeClaimTemplates:                     
  - metadata:
      name: minio-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi